# Site settings
title: A blog about learning cloud engineer.
description: A blog about learning cloud engineer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ditu Jaiswal
user_description: "Self-motivated, highly passionate, and hardworking fresher, with a profound interest in cloud computing, aiming for an opportunity to work in a challenging association to harness my skills and knowledge to strive for the growth of the association. Worked on a few personal projects based on python involving ask web framework and SQL-based database. I have a good knowledge of AWS and its introductory services in a beginner position. I have basic knowledge of Ansible and Docker. I have good operations skills and I am always open and enthusiastic about learning new technologies.
user_title: Cloud Practitioner
email: diti.jaiz8@gmail.com
twitter_username: aditi
github_username:  aditijaizwal
gplus_username:  na

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
